### ISSUE TITLE
com.facebook.accountkit:Error error 200

### ISSUE THREAD

**Issue by 1N50MN14** [prakashvadrevu/cordova-plugin-fb-accountkit#2]
On iOS (10.2) a successful phone login returns the following error:

`The operation couldn’t be completed. (com.facebook.accountkit:Error error 200.)`

**Comment by 1N50MN14** [comment]
nm

**Comment by EfosaSO** [comment]
Issue is solved [here](https://github.com/Mhusain/FacebookAccountKit/issues/2#issuecomment-270042493)
